/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClipboardActionBar: typeof import('./components/ClipboardActionBar.vue')['default']
    ClipboardEmptyState: typeof import('./components/clipboard-list/ClipboardEmptyState.vue')['default']
    ClipboardItemCard: typeof import('./components/clipboard-list/ClipboardItemCard.vue')['default']
    ClipboardList: typeof import('./components/ClipboardList.vue')['default']
    ClipboardListFilterPanel: typeof import('./components/clipboard-list/ClipboardListFilterPanel.vue')['default']
    ClipboardListHeader: typeof import('./components/clipboard-list/ClipboardListHeader.vue')['default']
    ClipboardLoadMore: typeof import('./components/clipboard-list/ClipboardLoadMore.vue')['default']
    ClipboardPreview: typeof import('./components/ClipboardPreview.vue')['default']
    ClipboardSection: typeof import('./components/clipboard-list/ClipboardSection.vue')['default']
    FullscreenLoadingOverlay: typeof import('./components/FullscreenLoadingOverlay.vue')['default']
    PageHolder: typeof import('./components/PageHolder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyncIndicator: typeof import('./components/SyncIndicator.vue')['default']
  }
}
